-- Table structure for table `review`
CREATE TABLE IF NOT EXISTS public.review (
    review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    review_text text NOT NULL,
    review_rating integer NOT NULL CHECK (review_rating >= 1 AND review_rating <= 5),
    review_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    inv_id integer NOT NULL,
    account_id integer NOT NULL,
    CONSTRAINT review_pkey PRIMARY KEY (review_id),
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id) 
        REFERENCES public.inventory (inv_id) 
        MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_account FOREIGN KEY (account_id) 
        REFERENCES public.account (account_id) 
        MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
);

-- Create index for faster lookups by inventory item
CREATE INDEX idx_review_inv_id ON public.review(inv_id);

-- Create index for faster lookups by account
CREATE INDEX idx_review_account_id ON public.review(account_id);

-- Sample review data (optional - for testing)
-- Note: You'll need to adjust account_id values based on your actual account data
-- INSERT INTO public.review (review_text, review_rating, inv_id, account_id)
-- VALUES 
--     ('This car is amazing! Great performance and looks stunning.', 5, 1, 1),
--     ('Good car but a bit pricey for what you get.', 4, 1, 2),
--     ('Absolutely love this vehicle! Best purchase ever.', 5, 2, 1);
